title: Muhammad Khalifa
name: "Muhammad Khalifa"
author: Muhammad Khalifa
twitter_username: mkhalifaaaa
baseurl: "/"
description: Recording some sparse bits on knowledge.
profile_url: "http://mohammadkhalifa.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
